java_plugin(
    name = "extension_plugin",
    generates_api = 1,
    processor_class = "org.pf4j.processor.ExtensionAnnotationProcessor",
    deps = [ "@maven//:org_pf4j_pf4j" ],
    visibility = ["//:__subpackages__"]
)